### ISSUE TITLE
Feedback on page: https://support.magento.com/hc/en-us/articles/360040296392

### ISSUE THREAD

**Issue by willoeden** [magento/knowledge-base#101]
### Article URL

https://support.magento.com/hc/en-us/articles/360040296392

### Description

Customers get reminders and also get a 30 day grace period, so normally when credentials stop working, it has been almost 60 days since payment should have been received. You can't open a new support ticket and deploy the application. After you get your license activated again, you still can't deploy the application.

^This is not accurate, our Entitlements Team does not provide any official grace periods at this time. Also, the last sentence is incorrect - once a customer's license is re-activated, they WILLL be able to deploy the application and do all the normal functions they usually do. This should be edited to:

*If you find this is due to an invoicing or lapsed contract issue, please contact your CSM for guidance to get this resolved. After your license is re-activated, your support and deployment entitlements will be restored.

### Content checklist

* The topic provides troubleshooting/best practice for ____.
* Information in this topic is relevant for
* Magento Commerce version  ____.
* Magento Commerce Cloud version  ____.
* Magento Open Source version  ____.
* Extension or technology (Fastly, New Relic etc) version   ____.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BarnyShergold** [comment]
This is a duplicate issue to #100 OR at best an extension of the same issue.

Please check #100 and update with additional information or continue the discussion.

This issue will be closed due to the duplication.
