### ISSUE TITLE
Feedback on page: https://support.magento.com/hc/en-us/articles/360029351531

### ISSUE THREAD

**Issue by rburkeatx** [magento/knowledge-base#105]
### Article URL

https://support.magento.com/hc/en-us/articles/360029351531

### Description

Step 16. Yes path takes you to https://dev.mysql.com/doc/refman/5.5/en/server-error-reference.html which is a dead link. Not sure what to do about it other than update the link (here would be an appropriate replacement): https://dev.mysql.com/doc/mysql-errors/5.7/en/server-error-reference.html

### Content checklist

* The topic provides troubleshooting/best practice for ____.
* Information in this topic is relevant for
* Magento Commerce version  ____.
* Magento Commerce Cloud version  ____.
* Magento Open Source version  ____.
* Extension or technology (Fastly, New Relic etc) version   ____.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by barnato-v** [comment]
@rburkeatx Link to https://github.com/magento-commerce/knowledge-base/pull/847

**Comment by barnato-v** [comment]
Internal ticket created KB-1365

**Comment by barnato-v** [comment]
Internal ticket KB-1365

**Comment by barnato-v** [comment]
Fixes https://github.com/magento-commerce/knowledge-base/pull/847
