### ISSUE TITLE
Feedback on page: src/troubleshooting/general/coupon-code-used-more-than-once-adobe-commerce.md

### ISSUE THREAD

**Issue by GreaterDiktakis** [magento/knowledge-base#111]
### Article URL

https://support.magento.com/hc/en-us/articles/4410911888013

### Description

The article indicates that this change is for Magento 2.3.6+ and 2.4.2+. However, I've checked the Commerce Base files and noticed that references to this new queue consumer only exists in 2.3.7+ and 2.4.3+.

Please verify and update the article accordingly

### Content checklist

* The topic provides troubleshooting/best practice for ____.
* Information in this topic is relevant for
* Magento Commerce version  ____.
* Magento Commerce Cloud version  ____.
* Magento Open Source version  ____.
* Extension or technology (Fastly, New Relic etc) version   ____.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jmenn** [comment]
Hi @GreaterDiktakis !

Thank you for your submission! We will check on this and let you know what we find.

**Comment by jmenn** [comment]
Internal ticket created: KB-1396

**Comment by jmenn** [comment]
@GreaterDiktakis We wanted to let you know that we are working on finding the answer to this question that you posed yet.

**Comment by jmenn** [comment]
@GreaterDiktakis We wanted to let you know that we edited the versioning of this article based on expert input.  Thank you for your feedback!
