### ISSUE TITLE
Feedback on page: https://support.magento.com/hc/en-us/articles/360017777431-Set-cache-TTL-for-images-and-other-static-content

### ISSUE THREAD

**Issue by jordanvector** [magento/knowledge-base#112]
### Article URL

https://devdocs.magento.com/cloud/project/set-cache.html

### Description

The guidance in this article is to set expires headers to -1 when in reality this doesn't tell cache to not expire, it tells nginx to NOT cache those files.  

For a cross reference, in another piece of documentation here https://devdocs.magento.com/cloud/project/magento-app-properties.html

we see 

`expires | Set the number of seconds to cache content in the browser. This key enables the cache-control and expires headers for static content. If this value is not set, the expires directive and resulting headers are not included when serving static content files. A negative 1 (-1) value results in no caching and is the default value. You can express time value with the following units: ms (milliseconds), s (seconds), m (minutes), h (hours), d (days), w (weeks), M (months, 30d), or y (years, 365d)`

So setting cache headers to -1 is doing the opposite of what it says it does in the Set cache TTL for images and other static content

### Content checklist

* The topic provides troubleshooting/best practice for ____.
* Information in this topic is relevant for
* Magento Commerce version  ____.
* Magento Commerce Cloud version  ____.
* Magento Open Source version  ____.
* Extension or technology (Fastly, New Relic etc) version   ____.

### Additional information/resources

We found this out the hard way on our magento cloud instance to not follow this recommendation and this documentation should be updated

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tanay-sharma** [comment]
Hi @jordanvector, thanks for pointing out the issue. Though the article you mentioned comes under the DevDocs team, and we can't make edits to that. You can raise this issue in the DevDocs Github repo. Link: https://github.com/magento-commerce/devdocs/wiki

**Comment by hostep** [comment]
@jordanvector: it's supposed to be this link I believe: https://github.com/magento/devdocs/wiki (the other link previously posted probably leads to some private repository that only Adobe employees have access to I'm guessing)
