### ISSUE TITLE
Feedback on page: https://support.magento.com/hc/en-us/articles/360048061192-SSL-TLS-certificates-for-Magento-Commerce-Cloud-FAQ

### ISSUE THREAD

**Issue by andrewmortiz** [magento/knowledge-base#113]
### Article URL

https://support.magento.com/hc/en-us/articles/360048061192-SSL-TLS-certificates-for-Magento-Commerce-Cloud-FAQ

### Description

The current wording on this article suggests a ticket needs to be created; however, this is incorrect:

If you have not launched a website yet, you may have received ACME Challenge CNAME from your Customer Technical Advisor (CTA). You only need an ACME challenge if you cannot immediately point your DNS to you production URL and need to get the SSL сertificates created in advance.

Once you add them to your DNS panel, submit a support ticket . We will validate that the CNAME has been added and apply the SSL certificate in response.

SSL Certificates are staged by automation within 12 hours of the addition of the CNAMEs.  See https://devdocs.magento.com/cloud/cdn/configure-fastly.html#provision-ssltls-certificates for reference. 

### Content checklist

This article provides quick answers to questions about getting SSL (TLS) certificates for your Magento Commerce Cloud site.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by almarchenko** [comment]
@andrewmortiz  thank you for your input! Sorry that it takes so long to process your issue. 
I'm verifying it now.
