### ISSUE TITLE
Invoices, shipments and credit memos not filtered according to admin timezone

### ISSUE THREAD

**Issue by atIOCrON** [magento/knowledge-base#116]
If you filter invoices, shipments or credit memos by date, the admin timezone is ignored, resulting in some incorrect records being displayed.

The below patch is confirmed working in v2.4.3-p1 for orders:

https://support.magento.com/hc/en-us/articles/4403024155917-MDVA-34330-Orders-not-filtered-according-to-admin-timezone

However, the same issue still persists for invoices, shipments and credit memos.

**Comment by almarchenko** [comment]
Hi @atIOCrON!

This repo is for the Knowledge Base articles and issues related to these articles.
Please report to magento/magento2 if it's a bug or if a problem.  If you are a paying customer, please report your issue to the Adobe Commerce Support as described here [Submit a support ticket](https://support.magento.com/hc/en-us/articles/360000913794#submit-ticket).

Thank you.
