### ISSUE TITLE
Feedback on page: src/faq/general/support-tools-overview.md

### ISSUE THREAD

**Issue by hrdeskariel** [magento/knowledge-base#120]
### Article URL

http://127.0.0.1/mysleephigh

### Description

Hello,

I am facing an issue in magento 2.4.2 version while uploading the product image on the client server. All code and database working fine on my localhost. But on Client server that is on Virtual Machine and using IIS server. Its not working properly.
Its uploaded on tmp folder but not fetching the product image on admin panel.

please help me to fine the solution for this.

![image](https://user-images.githubusercontent.com/94347209/150135279-a4b49b1f-399a-43f6-9056-fd0b564d704d.png)
![image](https://user-images.githubusercontent.com/94347209/150135384-cd091d58-f09d-42b8-a790-927287eca6dc.png)

### Content checklist

* The topic provides troubleshooting/best practice for .
* Information in this topic is relevant for
* Magento Commerce version  2.4.2.
* Magento Commerce Cloud version  ____.
* Magento Open Source version  ____.
* Extension or technology (Fastly, New Relic etc) version   ____.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by almarchenko** [comment]
Hey @hrdeskariel!

This repo is for the Knowledge Base articles and issues related to these articles.

Please report to [magento/magento2](https://github.com/magento/magento2) if it's a bug or if a problem.  If you are a paying customer, please report your issue to the Adobe Commerce Support as described here [Submit a support ticket](https://support.magento.com/hc/en-us/articles/360000913794#submit-ticket).

Thank you.
