### ISSUE TITLE
Feedback on page: src/best-practices/general/optimize-css-and-js-files-in-magento-commerce.md

### ISSUE THREAD

**Issue by ak77-prime** [magento/knowledge-base#122]
### Article URL

https://support.magento.com/hc/en-us/articles/360044482152

### Description

The Best Practices are not applicable to/will not work on Adobe Commerce Cloud - the indicated menus require either the Default or Development Magento modes - and these are hidden on the cloud environment which solely uses Production mode only

Adding a section under each configuration for Adobe Commerce Cloud:

- How to merge or minify CSS files?
**To enable CSS merging from the command line on Adobe Commerce Cloud:**
1. Run this command locally: ``bin/magento config:set --lock-config dev/css/merge_files 1``
2. Commit the app/etc/config.php file and redeploy
**To enable CSS minification from the command line on Adobe Commerce Cloud:**
1. Run this command locally: ``bin/magento config:set --lock-config dev/css/minify_files 1``
2. Commit the app/etc/config.php file and redeploy

- How to minify JS files?
**To enable JS minification from the command line on Adobe Commerce Cloud:**
1. Run this command locally: ``bin/magento config:set --lock-config dev/js/minify_files 1``
2. Commit the app/etc/config.php file and redeploy

### Content checklist

* The topic provides troubleshooting/best practice for ____.
* Information in this topic is relevant for
* Magento Commerce version  ____.
* Magento Commerce Cloud version  ____.
* Magento Open Source version  ____.
* Extension or technology (Fastly, New Relic etc) version   ____.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by almarchenko** [comment]
Internal issue KB-1443 created
