### ISSUE TITLE
Feedback on page: src/announcements/adobe-commerce-announcements/switching-to-opensearch-for-adobe-commerce-on-cloud-2.4.4.md

### ISSUE THREAD

**Issue by andrewmortiz** [magento/knowledge-base#124]
### Article URL

https://support.magento.com/hc/en-us/articles/4419942355725-Switching-to-OpenSearch-for-Adobe-Commerce-on-Cloud-2-4-4

### Description

Article lists Elasticsearch 7.10 as available in mid-Jan; however, it doesn't appear support for 7.10 is available yet. 

Will Adobe Commerce on cloud infrastructure support Elasticsearch 7.10?

Yes - starting mid-Jan.

https://devdocs.magento.com/cloud/project/services.html#service-versions / https://devdocs.magento.com/guides/v2.4/release-notes/bk-release-notes.html  

### Content checklist

* Extension or technology (Fastly, New Relic etc) version  Elastic Search / OpenSearch 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rinn22** [comment]
Just adding the jira ticket here: https://jira.corp.magento.com/browse/KB-1470

**Comment by Rinn22** [comment]
Smita Verma said, "We have added support for ES 7.10 in 2.4.3. The docs updated"

**Comment by Rinn22** [comment]
I got it confirmed from Smita Verma. The support is added on 2.4.3, the system requirement page is updated as well!
I am closing this issue.
