### ISSUE TITLE
Feedback on page: src/troubleshooting/known-issues-patches-attached/0-day-vulnerability-patch.md

### ISSUE THREAD

**Issue by KMangiere** [magento/knowledge-base#125]
### Article URL

https://support.magento.com/hc/en-us/articles/4426353041293-Security-updates-available-for-Adobe-Commerce-APSB22-12-

### Description
More thorough instructions for patching in the future would be appreciated.

**Comment by almarchenko** [comment]
Hey @KMangiere, thank you for your feedback! Do you mind giving more details? what kind of information do you think our articles are missing? 
Do you think more details are required in [How to apply a composer patch provided by Adobe](https://support.magento.com/hc/en-us/articles/360028367731) or do you think we should add steps for applying a non-composer patch?
Thank you.
