### ISSUE TITLE
Feedback on page: src/troubleshooting/general/checking-slow-queries-and-processes-mysql.md

### ISSUE THREAD

**Issue by mmalyshenko** [magento/knowledge-base#127]
### Article URL

https://support.magento.com/hc/en-us/articles/360030903091-Checking-slow-queries-and-processes-MySQL

### Description

Article expose Merchant Project ID, please use either randomized number to "ProjectID" instead

### Content checklist

* The topic provides troubleshooting/best practice for ____.
* Information in this topic is relevant for
* Magento Commerce version  ____.
* Magento Commerce Cloud version  ____.
* Magento Open Source version  ____.
* Extension or technology (Fastly, New Relic etc) version   ____.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tanay-sharma** [comment]
Thank you @mmalyshenko, I have created a ticket for this issue.

**Comment by almarchenko** [comment]
Issue is fixed.
