### ISSUE TITLE
Feedback on page: src/troubleshooting/general/the-security-scan-tool-report-is-blank.md

### ISSUE THREAD

**Issue by tompianta** [magento/knowledge-base#133]
### Article URL

https://support.magento.com/hc/en-us/articles/360029224131-The-Security-Scan-Tool-report-is-blank

### Description

ip subset seem not any more correct.

### Content checklist

* The topic provides troubleshooting/best practice for ____.
* Information in this topic is relevant for
* Magento Commerce version  ____.
* Magento Commerce Cloud version  ____.
* Magento Open Source version  ____.
* Extension or technology (Fastly, New Relic etc) version   ____.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tanay-sharma** [comment]
Thank you, @tompianta, for the submission! I have created a ticket: https://jira.corp.adobe.com/browse/MSKB-1490

**Comment by tanay-sharma** [comment]
The article has been updated: https://support.magento.com/hc/en-us/articles/360029224131-The-Security-Scan-Tool-report-is-blank
