### ISSUE TITLE
Feedback on page: src/how-to/general/sync-data-and-files-from-production-to-staging-or-staging-to-integration.md

### ISSUE THREAD

**Issue by ak77-prime** [magento/knowledge-base#134]
### Article URL

https://support.magento.com/hc/en-us/articles/360057150072

### Description

"This article explains how to synchronize your Production environment down to Staging on Adobe Commerce on cloud infrastructure; **this is possible via the user interface.**"

It should say ``this is not possible via the user interface``

### Content checklist

* The topic provides troubleshooting/best practice for ____.
* Information in this topic is relevant for
* Magento Commerce version  ____.
* Magento Commerce Cloud version  ____.
* Magento Open Source version  ____.
* Extension or technology (Fastly, New Relic etc) version   ____.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rinn22** [comment]
@ak77-prime Thank you. We will correct that ASAP.
Jira ticket: https://jira.corp.adobe.com/browse/MSKB-1522
