### ISSUE TITLE
Cannot download pro monitoring fact sheet -  Results in NOT FOUND

### ISSUE THREAD

**Issue by gamarshall** [magento/knowledge-base#141]
### Article URL

https://support.magento.com/hc/en-us/articles/assets/adobe_commerce_pro_monitoring_fact_sheet.pdf

### Description

Get a NOT FOUND when clicking on the link[ ](https://support.magento.com/hc/en-us/articles/assets/adobe_commerce_pro_monitoring_fact_sheet.pdf)

### Content checklist

* The topic provides troubleshooting/best practice for ____.
* Information in this topic is relevant for
* Magento Commerce version  ____.
* Magento Commerce Cloud version  ____.
* Magento Open Source version  ____.
* Extension or technology (Fastly, New Relic etc) version   ____.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tanay-sharma** [comment]
Hey @gamarshall, thanks for the submission. I have created a ticket for it: https://jira.corp.adobe.com/browse/MSKB-1568

**Comment by tanay-sharma** [comment]
Hi @gamarshall, the problem has been resolved. I am closing this issue.
