### ISSUE TITLE
Duplicated content related to Elasticsuite

### ISSUE THREAD

**Issue by romainruaud** [magento/knowledge-base#145]
# Issue: Topic clarification/correction
 
There are actually two different pages describing the same issue. They are duplicated : 

https://support.magento.com/hc/en-us/articles/360034921492-ElasticSuite-tracking-indices-causes-problems-with-Elasticsearch

=> I already contributed a lot more informations on this one, I think this is the one that should be kept.

https://support.magento.com/hc/en-us/articles/360035266131-Elasticsearch-with-ElasticSuite-crashes-or-out-of-memory

=> This is a duplicate of the previous one, can you delete this one ?

Regards

**Comment by tanay-sharma** [comment]
Hi @romainruaud, thanks for the submission. I have created a ticket for it. https://jira.corp.adobe.com/browse/MSKB-1592

**Comment by romainruaud** [comment]
@tanay-sharma 

you should first merge this PR which adds a lot of detail in the first article : https://github.com/magento/knowledge-base/pull/142

once it will be merged, it will be okay to delete the article that I asked to delete.

Regards
