### ISSUE TITLE
Admin Two Factor Email Notifications not being received

### ISSUE THREAD

**Issue by ak77-prime** [magento/knowledge-base#146]
# New topic request

## Description

Problem: You have set up Two-Factor Authentication in order to enhance Admin access security but aren't receiving the email with the instructions on completing the setup.

Cause: If you have not configured the Sender email properly, or your domain has not been white-labeled in Sendgrid, then the email would likely have ended up in the Spam folder

Troubleshooting:
Step 1: Check your Spam folder.
a. If the email didn't land in your Spam folder, run this Mysql query to verify the email addresses have been configured:
``select * from core_config_data where path like '%trans_email%';``
* If it doesn't return any results, it means that the Sender address had not been configured
* If it returns a result, proceed to Step 2

b. If the email had landed in your Spam folder, click on the link - if it has since expired, try logging in again to repeat the process
c. Once you have gained access, go to Stores > Configuration > General > Store Email Addresses and configure the email addresses

Step 2: If/once the email addresses have been properly configured, SSH into the environment and run this command:
```
php -r "mail(<your email address>,<subject>,<content>,'To: <sender email>');"
```
Check your Spam folder for this email - if it had email landed there, open a Support Ticket to request the domain to be white-labelled Sendgrid

## Content checklist

* Information in this topic is relevant for:
    * Magento Commerce Cloud version  ALL

**Comment by tanay-sharma** [comment]
Hi @ak77-prime, thank you for the submission. I have created a ticket for it: https://jira.corp.adobe.com/browse/MSKB-1593

**Comment by jmenn** [comment]
Completed!

Link:
https://support.magento.com/hc/en-us/articles/7348194378253
