### ISSUE TITLE
Error when upgrading to a version that supports PHP 8.1 on Cloud

### ISSUE THREAD

**Issue by ak77-prime** [magento/knowledge-base#147]
# New topic request

## Description

**Problem**: An error occurs during deployment when upgrading to a version that supports/requires PHP 8.1

```
E: Error parsing configuration files:
    - applications: Uncaught exception: The "json" extension is not supported for php:8.1
        at <script>:109:12
                      throw("The \"" + unsupported_extensions[0] + "\" extension is not supported for " + service.type);
                      ^

E: Error: Invalid configuration files, aborting build
```

**Cause**: PHP 8.1 already includes JSON support and doesn't require the extension to be installed separately

**Solution**: Remove json from the ``runtime`` > ``extensions`` section in .magento.app.yaml and redeploy

## Content checklist

* The topic provides troubleshooting/best practice for ____.
* Information in this topic is relevant for:
    * Magento Commerce Cloud version  2.4.4 and newer
    * Extension or technology (Fastly, New Relic etc) version   PHP 8.7.

## Additional information/resources
https://devdocs.magento.com/cloud/project/magento-app-php-application.html

**Comment by tanay-sharma** [comment]
Thanks for the submission, @ak77-prime. I have created a ticket for it: https://jira.corp.adobe.com/browse/MSKB-1594
