### ISSUE TITLE
Fix the command syntax for moving branches in the Cloud UI

### ISSUE THREAD

**Issue by ak77-prime** [magento/knowledge-base#148]
# Issue: Topic clarification/correction
 
## Topic Link
 
https://support.magento.com/hc/en-us/articles/4413750615565-Rearrange-cloud-branches-on-Adobe-Commerce
 
## Description
 
I had missed a flag (**-e**) in the command when I originally suggested this article - it should be:

```
magento-cloud environment:info -e <branch to move> parent <target parent>
```

 
## Additional information
 
reference issue: https://magento.zendesk.com/agent/tickets/532979

**Comment by jmenn** [comment]
Created ticket:
https://jira.corp.adobe.com/browse/MSKB-1632

**Comment by jmenn** [comment]
PR: https://github.com/magento-commerce/knowledge-base/pull/1299
Merged and complete!

Thank you for the submission, Anthony!
