### ISSUE TITLE
Add more information

### ISSUE THREAD

**Issue by ak77-prime** [magento/knowledge-base#149]
# Issue: Topic clarification/correction
 
## Topic Link
 
https://support.magento.com/hc/en-us/articles/6208159481229
 
## Description
 
Merchants might have inadvertently applied the MDVA-43443 over the one included with ECE Tools and could do with additional guidance on this topic.
 
## Additional information
 
I had a merchant report that they were able to apply the MDVA-43443 patch via the m2-hotfixes folder in spite of this article and asked whether the instructions were still valid.

I've found that the patch had been applied twice - once by ECE Tools (first occurrence) and the other via the m2-hotfixes folder:

```
$ vendor/bin/magento-patches -n status |grep 43443
║ MDVA-43443              │ Parser token new fix                                         │ Other           │ Adobe Commerce Support │ Applied     │ Patch type: Required                                     ║
║ N/A                     │ ../m2-hotfixes/MDVA-43443_EE_2.4.2-p2_COMPOSER_v1.patch      │ Other           │ Local                  │ Applied     │ Patch type: Custom                                       ║
```

I've verified the existence of this patch in ECE-Tools:

```
web@mymagento.0:~$ ls vendor/magento/magento-cloud-patches/patches |grep 43443
MDVA-43443__parser_token_new_fix__2.3.3-p1.patch
MDVA-43443__parser_token_new_fix__2.3.4-p2.patch
MDVA-43443__parser_token_new_fix__2.4.3.patch
```

So the answer/guidance would be as follows:

**Question:** I was able to apply MDVA-43443 via the m2-hotfixes folder - do I have to remove it as recommended in this article?

**Answer:**

1. Verify whether the patch has been applied (using the above command) ``vendor/bin/magento-patches -n status |grep 43443``
2. If it shows multiple results like this, then you should remove the MDVA-43443 patch from the m2-hotfixes folder

```
$ vendor/bin/magento-patches -n status |grep 43443
║ MDVA-43443              │ Parser token new fix                                         │ Other           │ Adobe Commerce Support │ Applied     │ Patch type: Required                                     ║
║ N/A                     │ ../m2-hotfixes/MDVA-43443_EE_2.4.2-p2_COMPOSER_v1.patch      │ Other           │ Local                  │ Applied     │ Patch type: Custom                                       ║
```

Future versions of Adobe Commerce will have already contained these patches, so it could cause the deployment to fail if they were to upgrade later.

**Comment by jmenn** [comment]
Thanks for this submission, @ak77-prime!

But I have questions!

1. This article you want changed
https://support.magento.com/hc/en-us/articles/6208159481229
is mainly for the MDVA-43395 patch, and only mentions the MDVA-43443 patch in passing in the Solution.

What needs to be changed for the MDVA-43395 patch part of this article, which is the most of this article?

2. This information you present suggests that this MDVA-43443 patch checking should be in its own article..... 

Are there any reasons why this should be in with this current article that concentrates on the MDVA-43395 patch (and not the MDVA-43443 patch) and not have these the MDVA-43395 patch checks in its own article?

**Comment by ak77-prime** [comment]
Nothing needs to be changed for MDVA-43395. These 2 patches are related and need to be applied on top of one another - you cannot apply MDVA-43443 without having first applied MDVA-43395

You can create a separate article for MDVA-43443 and then link it from the current one if it's beneficial doing it that way.

**Comment by jmenn** [comment]
https://jira.corp.adobe.com/browse/MSKB-1640
