### ISSUE TITLE
Fastly Error: Please check your Service ID and API token and try again.

### ISSUE THREAD

**Issue by ak77-prime** [magento/knowledge-base#150]
# New topic request

## Description

What to do if you get an error when validating the Fastly credentials

``Please check your Service ID and API token and try again.``

1. Verify that the credentials are valid using the API: https://devdocs.magento.com/cloud/cdn/configure-fastly.html#test-the-fastly-credentials:

``curl -H "Fastly-Key: <API key>" https://api.fastly.com/service/<service ID>/version/active``

2. If you get the same error, submit a Support request to request a new API Token. (Note: never share any passwords or valid/active API Tokens directly in the ticket as we will have to revoke the current token and generate a new one for security reasons.)

## Content checklist

* The topic provides troubleshooting/best practice for ____.
* Information in this topic is relevant for:
    * Magento Commerce version  All versions.
    * Magento Commerce Cloud version  All versions.
    * Magento Open Source version  N/A.
    * Extension or technology (Fastly, New Relic etc) version   Fastly.

## Additional information/resources

https://devdocs.magento.com/cloud/cdn/cloud-fastly.html#fastly-service-account-and-credentials
https://devdocs.magento.com/cloud/cdn/configure-fastly.html#test-the-fastly-credentials

**Comment by jmenn** [comment]
https://jira.corp.adobe.com/browse/MSKB-1641. -- Thanks @ak77-prime for this submission!

**Comment by barnato-v** [comment]
@Rinn22 looks like you completed the work for this issue by publishing the new topic [Error when validating the Fastly credentials](https://support.magento.com/hc/en-us/articles/7926801960589) - @jmenn so can we close this issue?
