### ISSUE TITLE
I am not seeing the expected number of SaaS Data Spaces

### ISSUE THREAD

**Issue by ak77-prime** [magento/knowledge-base#151]
# New topic request

## Description

**Either create a new topic or add the following to https://support.magento.com/hc/en-us/articles/360042224851**

**Problem**: I have configured the API keys for Sensei but I am only seeing 1 SaaS data space

**Answer:**
The number of SaaS data spaces that appears depends on your Commerce license:
Adobe Commerce - One production data space; two testing data spaces;
Magento Open Source - One production data space; no testing data spaces

Make sure:
* That the API keys were created on the Account Owner's account. Even if you have been given Shared Access to their account and created the keys on your own account, this will not grant you more than 1 data space
* If the keys were generated on the Account Owner's account, make sure that the license is active, i.e., there are no Pending invoices

## Content checklist

* The topic provides troubleshooting/best practice for configuring SaaS Data Spaces.
* Information in this topic is relevant for:
    * Magento Commerce version  **All versions**.
    * Magento Commerce Cloud version  **All versions**.
    * Magento Open Source version  **All versions**.
    * Extension or technology (Fastly, New Relic etc) version   Adobe Sensei (Product Recommendations/Live Search)

## Additional information/resources

https://support.magento.com/hc/en-us/articles/360042224851
https://docs.magento.com/user-guide/configuration/services/saas.html
https://experienceleague.adobe.com/docs/commerce-merchant-services/product-recommendations/getting-started/install-configure.html
Example ticket: https://magento.zendesk.com/agent/tickets/534795

**Comment by Rinn22** [comment]
Jira ticket is created: https://jira.corp.adobe.com/browse/MSKB-1645

**Comment by Rinn22** [comment]
The article is published: https://support.magento.com/hc/en-us/articles/7788037656845-I-ve-configured-API-keys-for-Sensei-but-only-seeing-one-SaaS-data-space

Closing this issue.
