### ISSUE TITLE
Problem: Unable to enter "shipping" as a URL key

### ISSUE THREAD

**Issue by ak77-prime** [magento/knowledge-base#153]
# New topic request

## Description

**Problem**: You are not able to use "shipping" as a URL key for products or CMS pages

**Cause**: This is because shipping is a reserved word defined in vendor/magento/module-shipping/etc/frontend/routes.xml

```
    <router id="standard">
        <route id="shipping" frontName="shipping">
            <module name="Magento_Shipping" />
        </route>
    </router>
```

**Solution**:
1. Enter a different URL key on the entity and save it
1. Go to Marketing > URL Rewrites
1. Create a custom URL Rewrite:
Request Path: shipping
Target Path: _the new URL key_
Redirect: No

## Content checklist

* The topic provides troubleshooting/best practice for ____.
* Information in this topic is relevant for:
    * Adobe Commerce on-premises version  2.4.x
    * Adobe Commerce on cloud infrastructure version  2.4.x
    * Magento Open Source version  ____.
    * Extension or technology (Fastly, New Relic etc) version   ____.

## Additional information/resources

**Comment by almarchenko** [comment]
Thank you @ak77-prime , internal ticket created.

**Comment by barnato-v** [comment]
@ak77-prime on it

**Comment by barnato-v** [comment]
Article published here https://support.magento.com/hc/en-us/articles/8631831300237
