### ISSUE TITLE
Where to find the Cloud Project Web UI

### ISSUE THREAD

**Issue by ak77-prime** [magento/knowledge-base#155]
# Issue: Topic clarification/correction
 
## Topic Link
 
https://support.magento.com/hc/en-us/articles/360000913794#ticket-fields-explained
 
## Description
 
The Cloud Project URL field description [section] is incomplete.

```
Please provide the URL for the Cloud Project Web UI, for example, https://<region>.magento.cloud/projects/<project-key>. If you have access to the [Onboarding UI](https://devdocs.magento.com/cloud/project/user-admin.html#cloud-user-webinterface), please make sure that you provide the Cloud Project Web UI specified there, not the URL to the Onboarding UI itself.
```
 
## Additional information
 
``The Cloud Project Web UI specified there`` - refers to ``https://cloud.magento.com/project/<xyz>/develop/infrastructure`` where ``<xyz>`` is the unique onboarding project ID

Another method to obtain the Project URL is as follows:

1. Login to https://accounts.magento.cloud/user
1. Click on the appropriate Project
1. Copy the URL

**Comment by Rinn22** [comment]
Thank you @ak77-prime. We will fix this shortly. 
jira ticket link: https://jira.corp.adobe.com/browse/MSKB-1692
