### ISSUE TITLE
Download of ACPLTSRV-2017-fix.sh patch doesn't work properly

### ISSUE THREAD

**Issue by jthelen-n98** [magento/knowledge-base#157]
# Issue: Topic clarification/correction
 
## Topic Link
 
https://support.magento.com/hc/en-us/articles/8214752983949-Packages-downgraded-after-upgrading-from-2-4-4-to-2-4-4-p1
 
## Description
 
When following the article's download link:

https://github.com/magento/knowledge-base/blob/main/src/troubleshooting/known-issues-patches-attached/assets/ACPLTSRV-2017-fix.sh?raw=true

one would expect the downloaded content to be a shell script to patch, but the content looks like this:

`bplist00�XUTI-Data�_$com.apple.traditional-mac-plain-text_public.utf8-plain-text_public.utf16-plain-textOACPLTSRV-2017-fix_ACPLTSRV-2017-fixO"ACPLTSRV-2017-fixB[u��	�`

**Comment by jmenn** [comment]
This was fixed soon after it was reported.

Verified download of shell script from the article page to double-check.

Complete!
