### ISSUE TITLE
Unable to login to Support or Cloud Project after migration to unified Adobe account access

### ISSUE THREAD

**Issue by ak77-prime** [magento/knowledge-base#158]
# New topic request

## Description

When you go to https://account.magento.com/customer/account/login/ or https://accounts.magento.cloud/user - you might notice that there is now a unified login form and you are no longer able to enter your credentials like you've been used to previously.

**After:**
![image](https://user-images.githubusercontent.com/68703716/184040700-0e7f1b6c-965a-4dcd-bddd-da19c2812348.png)

**Before:**
![image](https://user-images.githubusercontent.com/68703716/184042824-c78bc06b-8fa6-421d-b313-2e78fcb31e35.png)

**Problem**
I am unable to login to my [Adobe Commerce Support account](https://account.magento.com/customer/account/login/) or [Cloud account](https://accounts.magento.cloud/user)

**Solution**
As part of our process of integrating Adobe Commerce with other Adobe solutions, all users will need to create an Adobe login - if they don't already have one - using the same email address connected to their MageID. 

https://experienceleague.adobe.com/docs/commerce-admin/start/commerce-account/commerce-identity-manager.html?lang=en

You may log in to the account with either a) an existing Adobe corporate/personal account or b) if you don't have an Adobe account, create one with the same email address

## Content checklist

If the article provides a troubleshooting solution for an issue:

* Issue description (if relevant, steps to reproduce) This article explains how you would resolve the issue of not being able to login to your account.
* Solution
* Information in this article is relevant for: All users

**Comment by almarchenko** [comment]
https://jira.corp.adobe.com/browse/MSKB-1710

**Comment by barnato-v** [comment]
Article published here https://support.magento.com/hc/en-us/articles/8472095067021
