### ISSUE TITLE
In order to implement this, Starter projects cannot have any integration environments

### ISSUE THREAD

**Issue by ak77-prime** [magento/knowledge-base#159]
# Issue: Topic clarification/correction
 
## Topic Link
 
https://support.magento.com/hc/en-us/articles/360043032152
 
## Description
 
This is inaccurate:

```
The merchant needs to reduce the number of Integration branches to one, leaving only the Staging environments...
```

There can not be any Integration branches for Starter plans - they must ``delete the Integration environments and leave only the Staging environment.``

**Comment by jmenn** [comment]
Hi Anthony!
In regards to this:

For the Starter area:
1. This Starter #1 step just needs to be changed to reflect:
“they must delete the Integration environments and leave only the Staging environment.”
2.  Do any of the other Starter steps need to be changed?

**Comment by jmenn** [comment]
Ticket created:
https://jira.corp.adobe.com/browse/MSKB-1738

**Comment by ak77-prime** [comment]
> Hi Anthony! Thank you for the submission!
> 
> In regards to this:
> 
> For the Starter area:
> 
> 1. This Starter # 1 step just needs to be changed to reflect:
>    “they must delete the Integration environments and leave only the Staging environment.”
> 2. Do any of the other Starter steps need to be changed?

No other steps need to be changed. Only Pro can have 2 integration branches but Starter can't have any

**Comment by barnato-v** [comment]
@jmenn Looks like you updated the article titled Integration Environment enhancement request - Pro and Starter https://support.magento.com/hc/en-us/articles/360043032152 - can this Issue be closed?
