### ISSUE TITLE
Incorrect links

### ISSUE THREAD

**Issue by isitnikov** [magento/knowledge-base#162]
### Article URL

https://support.magento.com/hc/en-us/articles/4405637804301-Live-search-catalog-not-synchronized

### Description

Links in the text:

Steps to reproduce

Configure and connect Live Search for your Adobe Commerce instance as described in [Configure and Connect](https://devdocs-beta.magento.com/live-search/config-connect.html) in our developer documentation.
After 8 hours, verify the exported catalog data as described in [Configure and Connect > Verify catalog sync](https://devdocs-beta.magento.com/live-search/config-connect.html#verify-catalog-sync) in our developer documentation.
After 8 hours, test the connection as described in [Configure and Connect > Test the connection](https://devdocs-beta.magento.com/live-search/config-connect.html#test-the-connection) in our developer documentation.

follows to 404 pages.

### Content checklist

* The topic provides troubleshooting/best practice for ____.
* Information in this topic is relevant for
* Magento Commerce version  ____.
* Magento Commerce Cloud version  ____.
* Magento Open Source version  ____.
* Extension or technology (Fastly, New Relic etc) version   ____.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jmenn** [comment]
Thank you for the submission, @isitnikov!

I've created https://jira.corp.adobe.com/browse/MSKB-1745 for this issue.
