### ISSUE TITLE
Deprecated Functionality: stripos() Error on product edit from admin PHP 8.1 Magento 2.4.4

### ISSUE THREAD

**Issue by jivachetan** [magento/knowledge-base#165]
### Article URL

/app/vendor/magento/module-price-permissions/Observer/AdminhtmlBlockHtmlBeforeObserver.php

### Description

Error on Product edit from admin

Adobe Commerce:2.4.4
PHP: 8.1.6

Deprecated Functionality: stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /app/vendor/magento/module-price-permissions/Observer/AdminhtmlBlockHtmlBeforeObserver.php on line 125

### Content checklist

* The topic provides troubleshooting/best practice for AC 2.4.4.
* Information in this topic is relevant for AC 2.4.4
* Magento Commerce version  2.4.4.
* Magento Commerce Cloud version  2.4.4.
* Magento Open Source version  2.4.4.
* Extension or technology (Fastly, New Relic etc) version  PHP 8.1.6.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jivachetan** [comment]
This custom patch can fix this issue but not able to push on cloud

diff --git a/vendor/magento/module-price-permissions/Observer/AdminhtmlBlockHtmlBeforeObserver.php b/vendor/magento/module-price-permissions/Observer/AdminhtmlBlockHtmlBeforeObserver.php
index 974b4ec..2ac0e01 100644
--- a/vendor/magento/module-price-permissions/Observer/AdminhtmlBlockHtmlBeforeObserver.php
+++ b/vendor/magento/module-price-permissions/Observer/AdminhtmlBlockHtmlBeforeObserver.php
@@ -120,7 +120,7 @@ class AdminhtmlBlockHtmlBeforeObserver implements ObserverInterface

        /** @var $block Template */
        $block = $observer->getBlock();

        $this->_filterByBlockName($block);
-
+       if(empty($block->getNameInLayout())) { return; }
        // Handle prices that are shown when admin reviews customers shopping cart
-        if (stripos($block->getNameInLayout(), 'customer_cart_') === 0) {
+        if (empty($block->getNameInLayout()) || stripos($block->getNameInLayout(), 'customer_cart_') === 0) {

**Comment by almarchenko** [comment]
Hi @jivachetan!

This repo is for the Knowledge Base articles and issues related to these articles.
Your patch could be a good contribution in https://github.com/magento/quality-patches 
Thank you.
