### ISSUE TITLE
merging topics about account logins or adding links to related articles

### ISSUE THREAD

**Issue by ak77-prime** [magento/knowledge-base#167]
# Issue: Topic clarification/correction
 
## Topic Link
 
https://support.magento.com/hc/en-us/articles/360040954871
 
## Description
 
Could we possibly merge these articles:
[Link Magento.com, accounts.magento.cloud account logins](https://support.magento.com/hc/en-us/articles/360040954871)
[Unable to log in to Adobe Commerce support or cloud account](https://support.magento.com/hc/en-us/articles/8472095067021)

I have no idea how it would work though. Perhaps it would be better to just include a link to the second article, and also add a link to a second article, e.g.,:

**Related:**
[Unable to log in to Adobe Commerce support or cloud account](https://support.magento.com/hc/en-us/articles/8472095067021)
[Cannot access the correct cloud project](https://support.magento.com/hc/en-us/articles/6706549261709)

**Comment by barnato-v** [comment]
@ak77-prime Jiira ticket created here https://jira.corp.adobe.com/browse/MSKB-1775
