### ISSUE TITLE
non-clickable URLs in issue description

### ISSUE THREAD

**Issue by ak77-prime** [magento/knowledge-base#168]
# Issue: Topic clarification/correction
 
## Topic Link
 
https://support.magento.com/hc/en-us/articles/8472095067021
 
## Description
 
Is it intended to include the URLs in quotations?

```
When you go to 'https://account.magento.com/customer/account/login/' or 'https://accounts.magento.cloud/user' you might notice that there is now a unified login form and you are no longer able to enter your credentials like you have previously.
```
 
If not, then the actual links should be displayed instead.

**Comment by barnato-v** [comment]
Relates to https://github.com/magento/knowledge-base/issues/169

**Comment by barnato-v** [comment]
Completed in PR here https://github.com/magento-commerce/knowledge-base/pull/1400
