### ISSUE TITLE
Add a link to a Related article

### ISSUE THREAD

**Issue by ak77-prime** [magento/knowledge-base#169]
# Issue: Topic clarification/correction
 
https://support.magento.com/hc/en-us/articles/6706549261709
 
## Description
 
In the issue description, is the URL meant to be in quotations, rather than a link to the actual URL?

```
When you log in to your cloud account at https://accounts.magento.cloud/user,...
```

Also, could we add a link to another related article? E.g.,

**Related**
[Unable to log in to Adobe Commerce support or cloud account](https://support.magento.com/hc/en-us/articles/8472095067021)

**Comment by barnato-v** [comment]
@ak77-prime Thanks for this Anthony - Jira ticket created here https://jira.corp.adobe.com/browse/MSKB-1775
I think it is better if we go with the idea expressed in the [other issue ](https://github.com/magento/knowledge-base/issues/167)you submitted. This idea of yours was to merge the articles relating to accounts.

I will get approval from Sasha but assuming it doesn't produce a too-long article, I think it might be a good idea. Or doing a summary / index article with a list of articles on account problems in a table and link out?

**Comment by almarchenko** [comment]
@barnato-v  I would suggest we go simply with cross referencing

**Comment by barnato-v** [comment]
> @barnato-v I would suggest we go simply with cross referencing

@almarchenko Agreed. I have cross referenced the articles in the PR https://github.com/magento-commerce/knowledge-base/pull/1400

**Comment by barnato-v** [comment]
Completed in PR https://github.com/magento/knowledge-base/commit/2774996a689a9a1837fdfddc0d225a006dcce938
