### ISSUE TITLE
Server error message when trying to save changes to product

### ISSUE THREAD

**Issue by pdeboo** [magento/knowledge-base#172]
# General issue - website slow and non-responsive when saving product

## Description

 Product would update quickly (within 4-5 seconds) with no errors

## Additional information

[100522 Magento web errors.docx](https://github.com/magento/knowledge-base/files/9718090/100522.Magento.web.errors.docx)
see attached document

**Comment by pdeboo** [comment]
![image](https://user-images.githubusercontent.com/82110275/194148607-08316b42-a389-41da-b1a2-5269631c9d5d.png)

**Comment by pdeboo** [comment]
This should take 5-10 seconds - at most.  This is + 60 seconds and still going

![image](https://user-images.githubusercontent.com/82110275/194149018-ee71f824-df0a-449f-9b3a-e1543be4542a.png)

**Comment by jmenn** [comment]
Hi there @pdeboo - If you need to open a support ticket to address the particular issues you are experiencing while working with Adobe Commerce, the instructions to do so are here:
https://support.magento.com/hc/en-us/articles/360000913794#support-tickets

This is the Adobe Commerce Support Knowledge Base public repo, and not Adobe Commerce Support.
