### ISSUE TITLE
title has a typo: auto_increment_

### ISSUE THREAD

**Issue by ak77-prime** [magento/knowledge-base#173]
# Issue: Topic clarification/correction
 
## Topic Link
 
https://support.magento.com/hc/en-us/articles/360026909791
 
## Description
 
Fix the title - remove the extraneous _:

Database **auto_increment_** increment variable set to "3" Adobe Commerce on our cloud pro architecture

**Comment by jmenn** [comment]
Talked to @ak77-prime.

Got more info:

This title:
Database auto_increment_ increment variable set to “3” Adobe Commerce on our cloud pro architecture

Should be changed to this:
Database auto_increment increment variable set to “3" Adobe Commerce on our cloud pro architecture

**Comment by jmenn** [comment]
Fixed in https://jira.corp.adobe.com/browse/MSKB-1840. 
Anthony advised in Slack.
Complete.
