### ISSUE TITLE
Feedback on page: https://support.magento.com/hc/en-us/articles/4403109490317-Adobe-Commerce-Support-KB-starts-accepting-contributions

### ISSUE THREAD

**Issue by Fabulousemmy** [magento/knowledge-base#51]
# General issue

**Comment by almarchenko** [comment]
@Fabulousemmy  thank you for the input.
I'm not sure though what exactly is the issue with this article?

**Comment by almarchenko** [comment]
Closing this cause there has been no reply from you for more than 2 weeks.
