### ISSUE TITLE
Feedback on page: https://support.magento.com/hc/en-us/articles/360000913794

### ISSUE THREAD

**Issue by sidjain4you** [magento/knowledge-base#52]
# General issue

https://github.com/magento/magento2/issues/28159

We are getting this issue, while we are reindexing. Can you pls help?

**Comment by almarchenko** [comment]
Hi @sidjain4you, if you are a paying customer, please report your issue to the Adobe Commerce Support as described here [Submit a support ticket](https://support.magento.com/hc/en-us/articles/360000913794#submit-ticket).

This repo is for the Knowledge Base articles and issues related to these articles.
Thank you.
