### ISSUE TITLE
Feedback on page: https://support.magento.com/hc/en-us/articles/360000913794

### ISSUE THREAD

**Issue by dtavieres** [magento/knowledge-base#53]
# General issue
### **Compilation error. Same installation yesterday produced no error.**
Blocking issue. 

## Description
Clean installation Magento 2.4.2-p1  *Jul 27 2021*   No extension installed. 
Oracle Linux 8.4 Php 7.4 Apache 2.4 Mysql 8 

Compilation error. Same installation yesterday produced no error. 

Clean installation Magento 2.4.2-p1  *Jul 27 2021*   No extension installed. 
Oracle Linux 8.4 Php 7.4 Apache 2.4  

Please see the screen shot
https://prnt.sc/1gjybrr 

✘ magento2@stage5  /var/www/magento2/html  magento  se:di:c -vv
Compilation was started.
Interception cache generation... 6/9 [==================>---------]  66% 25 secs 346.0 MiBErrors during compilation:
	Magento\Framework\Setup\Option\AbstractConfigOption
		Incompatible argument type: Required type: int. Actual type: string; File:
/var/www/magento2/html/vendor/magento/framework/Setup/Option/AbstractConfigOption.php

Total Errors Count: 1

In Log.php line 92:

  [Magento\Framework\Validator\Exception]
  Error during compilation

Exception trace:
  at /var/www/magento2/html/setup/src/Magento/Setup/Module/Di/Compiler/Log/Log.php:92
 Magento\Setup\Module\Di\Compiler\Log\Log->report() at /var/www/magento2/html/setup/src/Magento/Setup/Module/Di/Code/Reader/Decorator/Interceptions.php:85
 Magento\Setup\Module\Di\Code\Reader\Decorator\Interceptions->getList() at /var/www/magento2/html/setup/src/Magento/Setup/Module/Di/App/Task/Operation/InterceptionCache.php:59
 Magento\Setup\Module\Di\App\Task\Operation\InterceptionCache->doOperation() at /var/www/magento2/html/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php:56
 Magento\Setup\Module\Di\App\Task\Manager->process() at /var/www/magento2/html/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php:216
 Magento\Setup\Console\Command\DiCompileCommand->execute() at /var/www/magento2/html/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /var/www/magento2/html/vendor/symfony/console/Application.php:1009
 Symfony\Component\Console\Application->doRunCommand() at /var/www/magento2/html/vendor/symfony/console/Application.php:273
 Symfony\Component\Console\Application->doRun() at /var/www/magento2/html/vendor/magento/framework/Console/Cli.php:115
 Magento\Framework\Console\Cli->doRun() at /var/www/magento2/html/vendor/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at /var/www/magento2/html/bin/magento:23

**Comment by BarnyShergold** [comment]
Why has this been reported here? A problem like this should be reported to magento/magento2 if it's a bug or if a problem, I would recommend discussion on the Magento Community Engineering Slack Channel?

This repo is all to do with maintaining the KnowledgeBase docs

**Comment by almarchenko** [comment]
@dtavieres  please report to magento/magento2 if it's a bug or if a problem.  If you are a paying customer, please report your issue to the Adobe Commerce Support as described here [Submit a support ticket](https://support.magento.com/hc/en-us/articles/360000913794#submit-ticket).

This repo is for the Knowledge Base articles and issues related to these articles.
Thank you.
