### ISSUE TITLE
Feedback on page: https://support.magento.com/hc/en-us/articles/360033020451-Data-Migration-Tool-troubleshooting

### ISSUE THREAD

**Issue by GenkiKenko** [magento/knowledge-base#54]
# General issue

**Comment by almarchenko** [comment]
@GenkiKenko what is exactly issue do you want to report? 
TY

**Comment by GenkiKenko** [comment]
I need support for installing the integrator HUB module!
The github link is from the file that includes the installer.
https://github.com/AnyMarket/magentoService

At.Marcus GENKI,


Em qui., 29 de jul. de 2021 às 14:34, Oleksandra Marchenko <
***@***.***> escreveu:

**Comment by almarchenko** [comment]
Please report to magento/magento2 if it's a bug or if a problem.  If you are a paying customer, please report your issue to the Adobe Commerce Support as described here [Submit a support ticket](https://support.magento.com/hc/en-us/articles/360000913794#submit-ticket).

This repo is for the Knowledge Base articles and issues related to these articles.
Thank you.
