### ISSUE TITLE
Update best practice article by replacing Magento Commerce with Adobe Commerce

### ISSUE THREAD

**Issue by almarchenko** [magento/knowledge-base#57]
# Issue: Topic clarification/correction
 
## Topic Link
 
https://support.magento.com/hc/en-us/articles/360049171211-Best-practices-for-render-blocking-resources-in-Magento-
 
## Description
 
1. Replace "Best practices for render-blocking resources in Magento" with "Best practices for render-blocking resources in Adobe Commerce" in title.
2. Replace "Magento Commerce, all supported versions" with "Adobe Commerce on-premise, all supported versions"
3. Replace "Magento Commerce Cloud, all supported versions" with "Adobe Commerce on our cloud infrastructure, all supported versions".
4. Replace "submit a Magento Support ticket." with "submit a support ticket." 
5. Replace "Magento User Guide > Optimizing Resource Files" with "Adobe Commerce User Guide > Optimizing Resource Files".

(don't change other links in Related reading for now)

**Comment by BarnyShergold** [comment]
@almarchenko - If we are going to do this on one page then really it should be done across the WHOLE KB. There are 611 .md files - do we want to undertake this now? Perhaps we should break the KB up into sections and do one at a time?
