### ISSUE TITLE
Feedback on page: https://support.magento.com/hc/en-us/articles/360038957591-Find-large-MySQL-tables

### ISSUE THREAD

**Issue by MeatPopsicle** [magento/knowledge-base#65]
# General issue

## Description

The current syntax is slightly misleading as inserting the 'project_id' directly will not return any results.
'%' should be used as a wildcard with the LIKE operator, for '=' these are not required.

## Possible solutions

Correct command should be as follows:
```
SELECT TABLE_NAME AS `Table`,
  ROUND((DATA_LENGTH + INDEX_LENGTH) / 1024 / 1024) AS `Size (MB)`
FROM information_schema.TABLES
WHERE TABLE_SCHEMA = "project_id"
ORDER BY (DATA_LENGTH + INDEX_LENGTH) DESC;
```

OR
```
SELECT TABLE_NAME AS `Table`,
  ROUND((DATA_LENGTH + INDEX_LENGTH) / 1024 / 1024) AS `Size (MB)`
FROM information_schema.TABLES
WHERE TABLE_SCHEMA LIKE "%project_id%"
ORDER BY (DATA_LENGTH + INDEX_LENGTH) DESC;
```

## Additional information

Nothing further.

**Comment by almarchenko** [comment]
@MeatPopsicle  thank you for the feedback. 
Would this the following be less confusing?

```
SELECT TABLE_NAME AS `Table`,
  ROUND((DATA_LENGTH + INDEX_LENGTH) / 1024 / 1024) AS `Size (MB)`
FROM information_schema.TABLES
WHERE TABLE_SCHEMA = <project_id>
ORDER BY (DATA_LENGTH + INDEX_LENGTH) DESC;

```

**Comment by MeatPopsicle** [comment]
Hi @almarchenko, thanks for getting back to me.

So running the above actually will not work as the "" (quotation marks) are required around the projectid. I would instead suggest the following:

SELECT TABLE_NAME AS `Table`,
  ROUND((DATA_LENGTH + INDEX_LENGTH) / 1024 / 1024) AS `Size (MB)`
FROM information_schema.TABLES
WHERE TABLE_SCHEMA = "<project_id>"
ORDER BY (DATA_LENGTH + INDEX_LENGTH) DESC;

And update the note to mention that <project_id> is to be replaced with the Cloud project ID for clarity :)

**Comment by almarchenko** [comment]
@MeatPopsicle  thanks! 
I've updated the article (it would take around 20 minutes for changes to be applied.)
