### ISSUE TITLE
Feedback on page: src/troubleshooting/general/mysql-high-load-bottleneck-in-magento-commerce-cloud.md

### ISSUE THREAD

**Issue by ak77-prime** [magento/knowledge-base#67]
### Article URL

https://support.magento.com/hc/en-us/articles/360037391972

### Description

Missing text in Project URL

```
For scaled architecture (split architecture), Redis slave connections SHOULD NOT be enabled. You can check if you are on scaled architecture by doing the following:

Go to your project URL, e.g. https://us.magento.cloud/projects/<MISSING>/environments/production
```

### Content checklist

* The topic provides troubleshooting/best practice for ____.
* Information in this topic is relevant for
* Magento Commerce version  ____.
* Magento Commerce Cloud version  ____.
* Magento Open Source version  ____.
* Extension or technology (Fastly, New Relic etc) version   ____.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by barnato-v** [comment]
change made to article here https://support.magento.com/hc/en-us/articles/360037391972
