### ISSUE TITLE
Feedback on page: src/troubleshooting/general/emails-not-being-sent-sendgrid-credits-exceeded.md

### ISSUE THREAD

**Issue by ak77-prime** [magento/knowledge-base#97]
### Article URL

https://support.magento.com/hc/en-us/articles/4409245779725

### Description

Adjust this paragraph to indicate that the credits are reset monthly for integration and Staging

```
SendGrid credits refer to the number of allowed emails that can be sent. Only 12,000 emails can be sent per month from the integration **and Staging** branches. Once you have reached that limit, you will have to wait until the next month to send emails again. There are no hard limits on the number of emails that can be sent in **Production**, as long as the Sender Reputation is over 95%.
```

In addition, append this paragraph/sentence:

```
Credits are renewed at the start of the month, so if you run out of credits, you will have to wait for the renewal.
```

### Content checklist

* The topic provides troubleshooting/best practice for ____.
* Information in this topic is relevant for
* Magento Commerce version  ____.
* Magento Commerce Cloud version  ____.
* Magento Open Source version  ____.
* Extension or technology (Fastly, New Relic etc) version   ____.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by barnato-v** [comment]
Internal ticket created KB-1332

**Comment by barnato-v** [comment]
PR here https://github.com/magento-commerce/knowledge-base/pull/819

**Comment by barnato-v** [comment]
Fixes #https://github.com/magento-commerce/knowledge-base/pull/819
