### ISSUE TITLE
Feedback on page: src/help-center-guide/help-center/magento-help-center-user-guide.md

### ISSUE THREAD

**Issue by ak77-prime** [magento/knowledge-base#98]
### Article URL

https://support.magento.com/hc/en-us/articles/360000913794-Magento-Help-Center-User-Guide#no-submit-link

### Description

In this section:

```
Issue
You access the Magento Help Center and want to submit a support request, but the Submit a ticket link is not displayed on the Help Center start page.

Cause
One of the following might be the cause:
* You have not logged in to the Help Center.
* If using shared access, you have not performed steps required to ensure that Magento Help Center is configured properly via the SSO call from Magento.com.
* Your account is not entitled for Magento Support (for example, you are not a paying Commerce customer or you are an Open Source customer).
```

This point needs to be fleshed out/expanded upon

``If using shared access, you have not performed steps required to ensure that Magento Help Center is configured properly via the SSO call from Magento.com.``

For example, emphasis on the ``for the first time``:

```
If using shared access for the first time, you have not performed the steps required to ensure that Magento Help Center is configured properly via the SSO call from Magento.com.
```

### Content checklist

* The topic provides troubleshooting/best practice for ____.
* Information in this topic is relevant for
* Magento Commerce version  ____.
* Magento Commerce Cloud version  ____.
* Magento Open Source version  ____.
* Extension or technology (Fastly, New Relic etc) version   ____.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by barnato-v** [comment]
Internal ticket created KB-1355
